# Generated by Django 4.2.7 on 2024-01-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes_cand',
            field=models.ManyToManyField(blank=True, null=True, related_name='candidates', to='Accounts.vote'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('P', 'President'), ('G', 'Governor'), ('S', 'Senator'), ('MP', 'Member Of Parliament')], help_text='Select post', max_length=100, verbose_name='Post Vieing For:'),
        ),
    ]
