# Generated by Django 4.2.7 on 2024-01-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_post_votes_cand_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes_cand',
        ),
    ]
